// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/sgokul961/echo-hub-chat-svc/pkg/api"
	"github.com/sgokul961/echo-hub-chat-svc/pkg/api/handler"
	"github.com/sgokul961/echo-hub-chat-svc/pkg/client"
	"github.com/sgokul961/echo-hub-chat-svc/pkg/config"
	"github.com/sgokul961/echo-hub-chat-svc/pkg/db"
	"github.com/sgokul961/echo-hub-chat-svc/pkg/repository"
	"github.com/sgokul961/echo-hub-chat-svc/pkg/usecase"
)

// Injectors from wire.go:

func InitApi(cfg config.Config) (*api.ServerHTTP, error) {
	database, err := db.ConnectMongo(cfg)
	if err != nil {
		return nil, err
	}
	chatRepository := repository.NewChatRepository(database)
	authServiceClient := client.NewAuthServiceClient(cfg)
	chatUseCase := usecase.NewChatUseCase(chatRepository, authServiceClient)
	chatHandler := handler.NewChatHandler(chatUseCase)
	serverHTTP := api.NewServerHttp(chatHandler)
	return serverHTTP, nil
}
